model_type: kernel

model_artifact_path: trained-models/kernel/${data.name}-laplacian-${ml_model.model_type}.pt

perform_training: ${perform_training}
perform_grid_search_hparams: ${perform_training_grid_search_hparams}

default_hparams:
  kernel: laplacian
  L: 0.5
  reg: 0.001
  version: kernel
  iters: 5
  egop_samples: 20000
  egop_batch_size: 2500